### ISSUE TITLE
Video sticker with transparent background

### ISSUE THREAD

**Issue by littlebear0729** [littlebear0729/telegram_sticker_downloader#1]
In telegram, video sticker is supposed to be downloaded as a `.webm` file.
At this moment, my sticker downloader program will treat transparent layer as black background while converting `.webm` format to `.gif`.
However, using `ffmpeg` command can render the alpha channel correctly in the convert process, and the command is as follow: `ffmpeg -c:v libvpx-vp9 -i "${filePath}" -f lavfi -i color=c=0xFFFFFF,format=rgb24 -filter_complex "[1][0]scale2ref[bg][vid];[bg][vid]overlay=format=rgb:shortest=1,setsar=1" -pix_fmt yuv420p -c:a copy "${filePath}.mp4" && ffmpeg -i "${filePath}.mp4" "${filePath}.gif"`

In fact, I'm not familiar with `ffmpeg` and don't know how to implement this script into my program.
If any one could help this, thanks a lot!

**Comment by mochaaP** [comment]
要不直接用 libavcodec 要不直接 spawn subprocess，封裝很多時候不太好用。

**Comment by littlebear0729** [comment]
> 要不直接用 libavcodec 要不直接 spawn subprocess，封裝很多時候不太好用。

我试试用subprocess实现后者吧。

**Comment by cyunrei** [comment]
经过查找一些资料发现，Telegram下载过后的`webm`文件里面包含多帧带alpha通道的图片，目前暂时没有找到可以直接从`ffmpeg`将其提取并转换成透明背景`gif`文件的方式。但可以采用另一种将`webm`中图片导出再合并的方式生成透明的`gif`文件。
以`test.webm`文件为例([telegram要求sticker视频编码为vp9](https://core.telegram.org/stickers#video-requirements))，使用ffmpeg作为提取图片，采用python中Pillow库(作为一种合并方式)对提取后的图片进行合成透明背景的gif实现方式如下：
1. 从`test.webm`文件提取带有alpha图层的图片
```bash
ffmpeg -c:v libvpx-vp9 -i test.webm  out/image_%d.png
```
2. 将提取后的alpha图层图片合成为透明背景的gif
```python
from PIL import Image
import os

def create_gif_from_images(input_dir, output_filename, duration=50, loop=0, transparency=0):
    image_files = sorted([f for f in os.listdir(input_dir) if f.endswith('.png')])

    frames = [Image.open(os.path.join(input_dir, filename)).convert('P') for filename in image_files]

    frames[0].save(output_filename, format='GIF',
                   append_images=frames[1:],
                   save_all=True,
                   duration=duration, loop=loop, transparency=transparency)

if __name__ == "__main__":
    input_directory = "out/"
    output_gif_filename = "output.gif"
    create_gif_from_images(input_directory, output_gif_filename)
```

**Comment by littlebear0729** [comment]
代码使用python重构，有望解决问题

**Comment by littlebear0729** [comment]
ffmpeg -c libvpx-vp9 -i test.webm -lavfi split[v],palettegen,[v]paletteuse out.gif
